# Generated by Django 5.0.3 on 2024-05-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='micromedidor',
            name='nuid',
            field=models.CharField(max_length=20, unique=True, verbose_name='NUID'),
        ),
    ]
